### ISSUE TITLE
Implement Ticket Details Cancel button functionality

### ISSUE THREAD

**Issue by CopperStarSystems** [CopperStarSystems/Tickinator#2]
As a technician
I want to be able to close the Ticket Details window without saving changes
So that I can view ticket details non-destructively

**Comment by kdavis89** [comment]
Well by god, let's see what we can do about that!

**Comment by CopperStarSystems** [comment]
Yup, exactly - in fact I'll be publishing design notes here in just a few minutes outlining the plan :)

**Comment by CopperStarSystems** [comment]
Issue 2:  Implement Ticket Detail Close Functionality
===========================================================
Refactor to introduce TicketDetailsViewModel

The TicketListItemViewModel was starting to get bogged down
with things that aren't really specific to a List view (things
like the upcoming CloseCommand, etc.).  This signals us that
we should have a more specialized VM for viewing ticket details
in the context of a dialog view.


ITicketDetailsViewModel
	ICommand CloseCommand
	...properties for Ticket properties...

TicketDetailsViewModel
	.ctor(Ticket ticket, ICloseCommand closeCommand)

ITicketDetailsViewModelFactory
	ITicketDetailsViewModel Create(Ticket ticket, ICloseCommand closeCommand)
	
TicketDetailsViewModelTests
	CloseCommand_Always_ReturnsInjectedValue

IClosable
	void Close()
	
IView : IClosable
	
ICloseCommandFactory
	ICloseCommand Create(IClosable closable)
	
ICloseCommand : ICommand

CloseCommand : GenericCommand<IClosable>, ICloseCommand
	[Stub]
	
CloseCommandTests [Stub]

===========================================================
ShowTicketDetailsCommand Implementation
	
ShowTicketDetailsCommand
	.ctor(..., ITicketDetailsViewModelFactory, ITicketRepository, ICloseCommandFactory)
	
	ExecuteInternal()
	...
	Retrieve Ticket from repository
	Create View
	Create CloseCommand(inject View)
	Create TicketDetailsViewModel from factory(inject CloseCommand)
	
ShowTicketDetailsCommandTests
	Update for new dependencies
	
===========================================================
CloseCommand Implementation

CloseCommand
	.ctor(IClosable closable)
	ExecuteInternal()
		invoke closable.Close()
		
CloseCommandTests
	Update CreateSystemUnderTest
	Execute_Always_PerformsExpectedWork
